"""added huge of columns on the tables and added news tables like Establishments_images

Revision ID: 25707fef9e1f
Revises: 
Create Date: 2024-10-13 14:52:03.087755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25707fef9e1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('establishments_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lugar', sa.Text(), nullable=False),
    sa.Column('estabelecimento_id', sa.Integer(), nullable=True),
    sa.Column('buffer_data', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('mimeType', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['establishments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employers', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('telefone',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('tipo_documento',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('numero_documento',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('data_nascimento',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('local_nascimento',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('funcao',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('contrato',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    with op.batch_alter_table('establishments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('msg_secundaria', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('horas_aberto', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('horas_fechado', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('dias_funcionamento', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('descricao_do_bairro', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('bairro', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('provincia', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('distrito', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('telefone', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=True))

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('preco',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('preco',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    with op.batch_alter_table('establishments', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('telefone')
        batch_op.drop_column('distrito')
        batch_op.drop_column('provincia')
        batch_op.drop_column('bairro')
        batch_op.drop_column('descricao_do_bairro')
        batch_op.drop_column('dias_funcionamento')
        batch_op.drop_column('horas_fechado')
        batch_op.drop_column('horas_aberto')
        batch_op.drop_column('msg_secundaria')

    with op.batch_alter_table('employers', schema=None) as batch_op:
        batch_op.alter_column('contrato',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('funcao',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('local_nascimento',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('data_nascimento',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('numero_documento',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('tipo_documento',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('telefone',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(),
               nullable=False)

    op.drop_table('establishments_images')
    # ### end Alembic commands ###
